apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: messaging-layer-poc
build:
  artifacts:
    - image: export-service-image
      context: messaging-poc-export
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
        env:
        - GOOGLE_RUNTIME_VERSION=17
        dependencies:
          ignore:
          - .idea
    - image: handler-service-image
      context: messaging-poc-handler
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
        env:
        - GOOGLE_RUNTIME_VERSION=17
manifests:
  rawYaml:
    - messaging-poc-export/k8s/service.yaml
    - messaging-poc-handler/k8s/service.yaml
