apiVersion: v1
kind: Service
metadata:
  name: export-service
spec:
  ports:
  - port: 8081
    name: http
  type: LoadBalancer
  selector:
    app: export-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: export-service
spec:
  selector:
    matchLabels:
      app: export-service
  template:
    metadata:
      labels:
        app: export-service
    spec:
      containers:
      - name: export-service
        image: export-service-image
        envFrom:
          - configMapRef:
              name: export-service-config
        ports:
          - containerPort: 8081
