apiVersion: v1
kind: Service
metadata:
  name: export-service
spec:
  ports:
  - port: 8081
    name: http
  type: LoadBalancer
  selector:
    app: export-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: export-service
spec:
  selector:
    matchLabels:
      app: export-service
  template:
    metadata:
      labels:
        app: export-service
    spec:
      containers:
      - name: export-service
        image: export-service-image
        env:
          - name: SERVICE_BUS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: service-bus-secrets
                key: SERVICE_BUS_CONNECTION_STRING
          - name: SERVICE_BUS_QUEUE_NAME
            valueFrom:
              secretKeyRef:
                name: service-bus-secrets
                key: SERVICE_BUS_QUEUE_NAME
          - name: AZURE_LOG_LEVEL
            value: "ERROR"
        ports:
          - containerPort: 8081
