apiVersion: v1
kind: Service
metadata:
  name: handler-service
spec:
  ports:
  - port: 8082
    name: http
  type: LoadBalancer
  selector:
    app: handler-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: handler-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: handler-service
  template:
    metadata:
      labels:
        app: handler-service
    spec:
      containers:
      - name: handler-service
        image: handler-service-image
        env:
          - name: SERVICE_BUS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: service-bus-secrets
                key: SERVICE_BUS_CONNECTION_STRING
          - name: SERVICE_BUS_QUEUE_NAME
            valueFrom:
              secretKeyRef:
                name: service-bus-secrets
                key: SERVICE_BUS_QUEUE_NAME
          - name: AZURE_LOG_LEVEL
            value: "ERROR"
        ports:
          - containerPort: 8082
